version: "3.7"
services:
    app:
        build:
            args:
                user: developer
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: nano
        container_name: nano-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - nano-network

    db:
        image: mysql:5.7
        container_name: nano-db
        restart: unless-stopped
        tty: true
        command: [--ignore-db-dir=lost+found]
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - nano-network

    nginx:
        image: nginx:alpine
        container_name: nano-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - nano-network

networks:
    nano-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
